all: dispatcher ambulance fire police maintenance

dispatcher: dispatcher.o 
	gcc -ggdb -o dispatcher dispatcher.o

ambulance: ambulance.o 
	gcc -ggdb -o ambulance ambulance.o
	
fire: fire.o 
	gcc -ggdb -o fire fire.o
	
police: police.o 
	gcc -ggdb -o police police.o
	
maintenance: maintenance.o 
	gcc -ggdb -o maintenance maintenance.o
